distro: Operate on DISTRO_FEATURES instead of DISTRO_FEATURES_DEFAULT
This is turned into an error to operate on DISTRO_FEATURES_DEFAULT in
latest oe-core

Fixes

ERROR: Variable DISTRO_FEATURES_DEFAULT is obsolete, add all default features to DISTRO_FEATURES_DEFAULTS (file: /home/ubuntu/yoe/sources/meta-yoe/conf/distro/wayland.inc line: 2 referenced as: DISTRO_FEATURES_DEFAULT:remove)
ERROR: Variable DISTRO_FEATURES_DEFAULT is obsolete, add all default features to DISTRO_FEATURES_DEFAULTS

Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>