yoe: Do not use gfortran or libgfortran in TOOLCHAIN_TARGET_TASK
Fixes

ERROR: buildtools-tarball-1.0-r0 do_populate_sdk: Unable to install packages. Command '/mnt/b/yoe/master/kas-build/tmp/work/x86_64-nativesdk-yoesdk-linux
buildtools-tarball/1.0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /mnt/b/yoe/master/kas-build/tmp/work/x86_64-nativesdk-yoesdk-linux/buildtools-
tarball/1.0/opkg-sdk-target.conf -t /mnt/b/yoe/master/kas-build/tmp/work/x86_64-nativesdk-yoesdk-linux/buildtools-tarball/1.0/temp/ipktemp/ -o /mnt/b/yoe/
master/kas-build/tmp/work/x86_64-nativesdk-yoesdk-linux/buildtools-tarball/1.0/sdk/image/usr/local/oe-sdk-hardcoded-buildpath/sysroots/none  --force-
postinstall --prefer-arch-to-version   install libgfortran' returned 255:

error: opkg_prepare_url_for_install: Couldn't find anything to satisfy 'libgfortran'.

libgfortran is a generated package.
The reason it's not found might be that it's not in /mnt/b/yoe/master/kas-build/tmp/work/x86_64-nativesdk-yoesdk-linux/buildtools-tarball/1.0/oe-rootfs-repo

Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>