Layer Updates: sources/meta-arm sources/meta-clang sources/meta-intel sources/meta-openembedded sources/meta-qcom sources/meta-qt6 sources/meta-tegra sources/meta-variscite-bsp sources/meta-variscite-bsp-common sources/openembedded-core
* sources/meta-arm 1c86990f...08542e22 (2):
  > gn: Delete
  > arm/trusted-firmware-a: Re-enable BL31 console by default

* sources/meta-clang c467153...12b3901 (1):
  > ci: Remove paths for sstate-cache-management.py

* sources/meta-intel f7ba543c...2740652f (1):
  > ipmctl: fix build issue undefined reference to `main`

* sources/meta-openembedded f71c0f655a...1e4cd01f22 (22):
  > DO NOT MERGE: Add Github actions CI workflow
  > touchpademulator: Add recipe
  > meta-python/conf/layer.conf: update OEQA_REPRODUCIBLE_EXCLUDED_PACKAGES
  > python3-pandas: fix reproducibility issue
  > python3-mlcommons-loadgen: support reproducibility
  > python3-yarl: support reproducibility
  > python3-propcache: support reproducibility
  > python3-frozenlist: support reproducibility
  > taisei: Add packageconfigs for lto and rtti
  > taisei: Upgrade to 1.4.4 release
  > usbids: upgrade 2025.04.01 -> 2025.09.15
  > openocd: add dmem support to am64xx and j784s4 platforms
  > openocd: bump the openocd, jimtcl versions
  > perfetto: Use gn from native sysroot
  > mariadb: 11.4.8
  > mariadb: Fix a crash in my_convert()
  > nspr: upgrade 4.36 -> 4.37
  > rygel: update 44.1 -> 45.0
  > neon: upgrade 0.33.0 -> 0.34.2
  > udisks2: upgrade 2.10.1 -> 2.10.2
  > dracut: Fix the multi-lib config
  > webkitgtk3: add patch to fix qemuarm

* sources/meta-qcom 7c96f42...0813a9f (5):
  > IQ-8275-EVK (RB4) enablement (#1095)
  > initramfs-test-image: provide clinfo and vulkaninfo (#1111)
  > packagegroup-qcom: drop msm-gbm-backend from RDEPENDS (#1110)
  > ci: fix job/steps definition (#1112)
  > ci: clean up sstate cache with a dedicated monthly job (#1109)

* sources/meta-qt6 7d4a2bc5...1c7a2e01 (10):
  > qtquick3d: Fix build on riscv32
  > qtwebengine: Backport a chromium fix for clang-21
  > qtwebengine: Disable building on musl targets
  > Bump version to 6.10.1
  > Update submodule refs on '6.10' in yocto/meta-qt6
  > qmake: fix path to external host bins
  < Merge pull request #95 from YoeDistro/kraj/6.10
  < qtquick3d: Fix build on riscv32
  < qtwebengine: Backport a chromium fix for clang-21
  < qtwebengine: Disable building on musl targets

* sources/meta-tegra 9e73d983...2036dab6 (3):
  > tegra-uefi-keys-dtb: nullify do_install task
  > image_types_tegra.bbclass: update check for UefiUpdateSecurityKeys overlay
  > fix: update image_types_tegra task dependency for uefi keys dtb

* sources/meta-variscite-bsp 6b09548...637cf88 (66):
  < Merge pull request #46 from YoeDistro/kraj/mickledore-var02
  > gstreamer1.0-plugins-bad: Upgrade bbappend to match 1.26 release
  < Merge pull request #45 from YoeDistro/kraj/mickledore-var02
  > freertos-variscite: Fix build with cmake4+ and whinlatter release
  > cortexm-toolchain-cross: Fix build with whinlatter
  > imx-sc-firmware: Do not hardcode 'git' in paths
  > freertos-variscite: Remove setting S
  > u-boot-common: Adjust for S moving into UNPACKDIR in whinlatter release
  > udev-extraconf: Keep defaults for UNPACKDIR
  < Merge pull request #44 from YoeDistro/kraj/mickledore-var02
  > Add whinlatter (5.3) to compatible layer series
  < Merge pull request #43 from YoeDistro/kraj/mickledore-var02
  > firmware-nxp-wifi: Keep old file name of nxp8997 and nxp9098
  > libubootenv: Drop patch to increase line length to 4096
  > layer.conf: Update to walnascar (5.2) layer/release series
  > imx-boot: Replace BOOT_NAME with imx-boot
  > layer.conf: Add styhead as compatible layer
  > bluealsa: Rename bbappend to use wildcard
  > gstreamer1.0-plugins-bad: Move bbappend to match meta-freescale version 1.24 now
  > imx-atf: Make bbappend version independent
  > pm-utils-variscite,u-boot-splash: Drop redundant S settings
  > recipes: Implement WORKDIR -> UNPACKDIR transition
  > base-files: Use UNPACKDIR
  > gstreamer1.0-plugins-bad: Rename to include 1.22.5.imx as well
  > variscite: Enable optee machine feature on iMX8/IMX9 based machines
  > linux-variscite: Define KERNEL_DEVICETREE_32BIT_COMPATIBILITY_UPDATE
  > imx-boot: Adjust for changes in do_compile in meta-freescale
  > layer.conf: Make is scarthgap compatible
  > libubootenv: Refresh patch to apply to mickledore-var02
  > firmware-nxp-wifi: Pin LIC_FILES_CHKSUM for var-som
  < Merge pull request #42 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #41 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #40 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #39 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #38 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #37 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #36 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #35 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #34 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #33 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #32 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #31 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #30 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #29 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #28 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #27 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #26 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #25 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #24 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #23 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #22 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #21 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #20 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #19 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #18 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #17 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #16 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #15 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #14 from YoeDistro/kraj/mickledore-var02
  < gstreamer1.0-plugins-bad: Rename to include 1.22.5.imx as well
  < variscite: Enable optee machine feature on iMX8/IMX9 based machines
  < linux-variscite: Define KERNEL_DEVICETREE_32BIT_COMPATIBILITY_UPDATE
  < imx-boot: Adjust for changes in do_compile in meta-freescale
  < layer.conf: Make is scarthgap compatible
  < libubootenv: Refresh patch to apply to mickledore-var02
  < firmware-nxp-wifi: Pin LIC_FILES_CHKSUM for var-som

* sources/meta-variscite-bsp-common 5e73e7c...14d2f53 (14):
  < Merge pull request #6 from YoeDistro/kraj/mickledore-var02
  > var-mii: Remove setting S
  < Merge pull request #5 from YoeDistro/kraj/mickledore-var02
  > Add whinlatter (5.3) to compatible layer series
  < Merge pull request #4 from YoeDistro/kraj/mickledore-var02
  > layer.conf: Add walnascar as compatible layer
  > layer.conf: Add styhead as compatible layer
  > recipes: Drop setting S = WORKDIR and replace WORKDIR with UNPACKDIR
  > layer.conf: Add scarthgap to layer compat
  > conf: Correct BBFILE_PRIORITY for variscite-bsp-common
  < Merge pull request #3 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #2 from YoeDistro/kraj/mickledore-var02
  < Merge pull request #1 from YoeDistro/kraj/mickledore-var02
  < layer.conf: Add scarthgap to layer compat

* sources/openembedded-core cf1972b7b9...bc723f443f (30):
  > clang: use llvm recipe
  > llvm: add recipe for just the LLVM libraries
  > clang: globally disable build-time RPATHs for reproducibility
  > linux-firmware: skip ldflags sanity check
  > python3-lxml: upgrade 6.0.1 -> 6.0.2
  > spirv-llvm-translator: Upgrade to 21.1.1
  > clang: Upgrade to 21.1.2 release
  > libpam: Fix build with LLD linker
  > bitbake.conf: Filter in ld-is-lld to nativesdk recipes
  > python3-numpy: Enable rvv with clang on riscv
  > ptests: Enable python3-numpy on riscv64
  > qemux86: Add identical qemux86copy variant for tests
  > XXX: Bump ccache size to 200G Max
  > populate_sdk_ext: do not require CONF_VERSION (e.g. local.conf version) to be set
  > ghostscript: upgrade 10.05.1 -> 10.06.0
  > package.py: replace all files unconditionally when copy debug sources
  > linux-firmware: Fix FILES for intel firmware
  > clang: build with MinSizeRel
  > clang: fix reproducibility issue in LLVMConfig.cmake
  > clang: use EXTRA_OECMAKE +=
  > gn: Add recipe
  > musl: Update to tip of trunk
  > cargo-c: update 0.10.15 -> 0.10.16
  > sanity: Update minimum gcc version to 10.1
  > linux-firmware: backport the topology rename patch
  > bluez5: fix Bluetooth LE audio regression
  > shadow: Increase the maximum group name length to 32 (the default)
  > meson: upgrade to 1.9.1
  > xkeyboard-config: Turn absolute symlinks into relative
  > build-appliance-image: Update to master head revision

Signed-off-by: Khem Raj <raj.khem@gmail.com>