yoe: Do not make clang provide for llvm
LLVM is now an independent recipe, so there is not
chance of conflicts and a policy to prefer one is
no longer needed.

This also avoids parsing loop

ERROR: Task virtual:native:/mnt/b/yoe/master/sources/poky/meta/recipes-devtools/clang/clang_git.bb:do_collect_spdx_deps has circular dependency on virtual:native:/mnt/b/yoe/master/sources/poky/meta/recipes-devtools/clang/clang_git.bb:do_create_spdx

Signed-off-by: Khem Raj <raj.khem@gmail.com>