yoe: Always use psplash from core
meta-rpi provides its own now defunct psplash-raspberrypi which causes
builds to fail

ERROR: Nothing RPROVIDES 'psplash-raspberrypi' (but /home/khem/actions-runner-yoe/_work/yoe-distro/yoe-distro/sources/meta-yoe/recipes-core/images/yoe-qt5-image.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'psplash-raspberrypi' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['psplash-raspberrypi']
ERROR: Required build target 'yoe-qt5-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['yoe-qt5-image', 'psplash-raspberrypi']

Signed-off-by: Khem Raj <raj.khem@gmail.com>